// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkyukgqxmacgkyjobiso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreXVrZ3F4bWFjZ2t5am9iaXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTk3ODEsImV4cCI6MjA3MTc3NTc4MX0.p4V-D_rs3upR43wTeX8hb8yJDsvJcdTHlsFepIAKxRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});